baseURL = "https://yxs.github.io/"
languageCode = "en-us"
title = "Xuesong Ye 叶雪松"
theme = "PaperMod"

# SEO
enableRobotsTXT = true

[minify]
  disableXML = true
  minifyOutput = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

[permalinks]
  posts = "/:year/:month/:slug/" 

[params]
  mainSections = []
  
  author = "Xuesong Ye"
  
  DateFormat = "January 2, 2006"
  defaultTheme = "auto"
  disableThemeToggle = false

  ShowReadingTime = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowWordCount = true

  UseHugoToc = true
  showtoc = true
  tocopen = false

  comments = true

[menu]

  [[menu.main]]
    identifier = "github"
    name = "GitHub"
    url = "https://github.com/yxs"
    weight = 10

  [[menu.main]]
    identifier = "scholar"
    name = "Google Scholar"
    url = "https://scholar.google.com/citations?user=wVboVZwAAAAJ"
    weight = 20

  [[menu.main]]
    identifier = "x"
    name = "X"
    url = "https://x.com/XuesongYe"
    weight = 30

  [[menu.main]]
    identifier = "linkedin"
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/xuesongye/"
    weight = 40

  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/posts/"
    weight = 50

[markup]
  [markup.highlight]
    noClasses = false
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true